/**
 * Acciones
 */
export const SET_FIREBASE_DATA = 'SET_FIREBASE_DATA';

export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';
export const SET_FILTER_AUTHOR = 'SET_FILTER_AUTHOR';
export const SET_FILTER_GENRE = 'SET_FILTER_GENRE';
export const SET_FILTER_SAGA = 'SET_FILTER_SAGA';

export const SET_PREVIOUS_ROUTE = 'SET_PREVIOUS_ROUTE';
export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE';
